# Makefile extensions for windows.

# -----------------------------------------------------------------------------
# Variables
# -----------------------------------------------------------------------------

GO_BUILDMODE := "-buildmode=exe"
SENZING_TOOLS_DATABASE_URL ?= sqlite3://na:na@nowhere/C:\Temp\sqlite\G2C.db

# -----------------------------------------------------------------------------
# Makefile targets supported by all platforms.
# -----------------------------------------------------------------------------

.PHONY: hello-world
hello-world:
	@echo "Hello World, from windows."

# -----------------------------------------------------------------------------
# Build
# -----------------------------------------------------------------------------

.PHONY: build
build: windows/amd64
	@mv $(TARGET_DIRECTORY)/windows-amd64/$(PROGRAM_NAME) $(TARGET_DIRECTORY)/windows-amd64/$(PROGRAM_NAME).exe

# -----------------------------------------------------------------------------
# Test
# -----------------------------------------------------------------------------

.PHONY: test
test:
	@go test -v -p 1 ./...
#	@go test -v -p 1 ./.
#	@go test -v -p 1 ./g2config
#	@go test -v -p 1 ./g2configmgr
#	@go test -v -p 1 ./g2diagnostic
#	@go test -v -p 1 ./g2engine
#	@go test -v -p 1 ./g2product

# -----------------------------------------------------------------------------
# Run
# -----------------------------------------------------------------------------

.PHONY: run
run:
	@go run main.go

# -----------------------------------------------------------------------------
# Utility targets
# -----------------------------------------------------------------------------

.PHONY: clean-osarch-specific
clean-osarch-specific:
#	del /f /s /q $(TARGET_DIRECTORY)
#	del /f /s /q $(GOPATH)/bin/$(PROGRAM_NAME)

.PHONY: mkdir-target
mkdir-target:
	@mkdir $(TARGET_DIRECTORY)\
	@mkdir $(TARGET_DIRECTORY)\$(GO_OS)-$(GO_ARCH)


.PHONY: setup
setup:
	@rmdir /S /Q C:\Temp\sqlite
	@mkdir C:\Temp\sqlite
	@copy testdata\sqlite\G2C.db C:\Temp\sqlite\G2C.db

# -----------------------------------------------------------------------------
# Makefile targets supported only by this platform.
# -----------------------------------------------------------------------------

.PHONY: only-windows
only-windows:
	@echo "Only windows has this Makefile target."
