# Makefile extensions for linux.

# -----------------------------------------------------------------------------
# Variables
# -----------------------------------------------------------------------------

# Conditional assignment. ('?=')
# Can be overridden with "export"
# Example: "export LD_LIBRARY_PATH=/path/to/my/senzing/g2/lib"

LD_LIBRARY_PATH ?= /opt/senzing/g2/lib

# -----------------------------------------------------------------------------
# Makefile targets supported by all platforms.
# -----------------------------------------------------------------------------

.PHONY: hello-world
hello-world:
	@echo "Hello World, from linux."

# -----------------------------------------------------------------------------
# Build
# -----------------------------------------------------------------------------

.PHONY: build
build: linux/amd64

# -----------------------------------------------------------------------------
# Test
# -----------------------------------------------------------------------------

.PHONY: test
test: setup
	@go test -v -p 1 ./...
#	@go test -v ./.
#	@go test -v ./g2config
#	@go test -v ./g2configmgr
#	@go test -v ./g2diagnostic
#	@go test -v ./g2engine
#	@go test -v ./g2product

# -----------------------------------------------------------------------------
# Run
# -----------------------------------------------------------------------------

.PHONY: run
run:
	@go run main.go

# -----------------------------------------------------------------------------
# Makefile targets supported only by this platform.
# -----------------------------------------------------------------------------

.PHONY: only-linux
only-linux:
	@echo "Only linux has this Makefile target."
