//go:build linux

package szengine_test

var expectedExportCsvEntityReport = []string{
	`RESOLVED_ENTITY_ID,RELATED_ENTITY_ID,MATCH_LEVEL_CODE,MATCH_KEY,DATA_SOURCE,RECORD_ID`,
	`3,0,"","","CUSTOMERS","1001"`,
	`3,0,"RESOLVED","+NAME+DOB+PHONE","CUSTOMERS","1002"`,
	`3,0,"RESOLVED","+NAME+DOB+EMAIL","CUSTOMERS","1003"`,
}

var expectedExportCsvEntityReportIterator = []string{
	`RESOLVED_ENTITY_ID,RELATED_ENTITY_ID,MATCH_LEVEL_CODE,MATCH_KEY,DATA_SOURCE,RECORD_ID`,
	`18,0,"","","CUSTOMERS","1001"`,
	`18,0,"RESOLVED","+NAME+DOB+PHONE","CUSTOMERS","1002"`,
	`18,0,"RESOLVED","+NAME+DOB+EMAIL","CUSTOMERS","1003"`,
}

var expectedExportCsvEntityReportIteratorNilCsvColumnList = []string{
	`RESOLVED_ENTITY_ID,RELATED_ENTITY_ID,MATCH_LEVEL_CODE,MATCH_KEY,DATA_SOURCE,RECORD_ID`,
	`24,0,"","","CUSTOMERS","1001"`,
	`24,0,"RESOLVED","+NAME+DOB+PHONE","CUSTOMERS","1002"`,
	`24,0,"RESOLVED","+NAME+DOB+EMAIL","CUSTOMERS","1003"`,
}

var expectedRedoRecordCount = int64(0)
