name: Go proxy pull

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions: {}

jobs:
  go-proxy-pull:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Pull new module version
        uses: andrewslotin/go-proxy-pull-action@v1.4.0
        with:
          import_path: github.com/${{ github.repository }}

      - name: Notify Slack on failure
        if: failure() || cancelled()
        uses: senzing-factory/build-resources/slack-failure-notification@v4
        with:
          job-status: ${{ job.status }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
