name: Go test windows

on: 
  push:
    branches: "path-test"

env:
  SENZING_LOG_LEVEL: TRACE
  SENZING_TOOLS_DATABASE_URL: "sqlite3://na:na@nowhere/C:\\Temp\\sqlite\\G2C.db"

permissions:
  contents: read

jobs:
  go-test-windows:
    name: "Go test with Senzing: ${{ matrix.senzingapi-version }}; OS: ${{ matrix.os }}; Go: ${{ matrix.go }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.21"]
        os: [windows-latest]
        senzingapi-version: [staging-v4]

    steps:

      - name: Add to "Path" environment variable
        run: |
          echo "$Env:PATH=$Env:PATH;C:\Program Files\senzing\er\lib" >> $env:GITHUB_ENV

      - name: print path
        run: |
          gc $env:GITHUB_PATH | write-output

